/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atrib Aux</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.go.GoPackage#getAtrib_Aux()
 * @model
 * @generated
 */
public interface Atrib_Aux extends EObject
{
} // Atrib_Aux
