/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.go.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cases</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.go.Cases#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.go.go.Cases#getV <em>V</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.go.GoPackage#getCases()
 * @model
 * @generated
 */
public interface Cases extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' containment reference.
   * @see #setX(Expression)
   * @see org.xtext.go.go.GoPackage#getCases_X()
   * @model containment="true"
   * @generated
   */
  Expression getX();

  /**
   * Sets the value of the '{@link org.xtext.go.go.Cases#getX <em>X</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' containment reference.
   * @see #getX()
   * @generated
   */
  void setX(Expression value);

  /**
   * Returns the value of the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>V</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' containment reference.
   * @see #setV(Greeting)
   * @see org.xtext.go.go.GoPackage#getCases_V()
   * @model containment="true"
   * @generated
   */
  Greeting getV();

  /**
   * Sets the value of the '{@link org.xtext.go.go.Cases#getV <em>V</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' containment reference.
   * @see #getV()
   * @generated
   */
  void setV(Greeting value);

} // Cases
