/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.go.Condition#getIf <em>If</em>}</li>
 *   <li>{@link org.xtext.go.go.Condition#getElseif <em>Elseif</em>}</li>
 *   <li>{@link org.xtext.go.go.Condition#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.go.GoPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends Greeting
{
  /**
   * Returns the value of the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' containment reference.
   * @see #setIf(IfCondition)
   * @see org.xtext.go.go.GoPackage#getCondition_If()
   * @model containment="true"
   * @generated
   */
  IfCondition getIf();

  /**
   * Sets the value of the '{@link org.xtext.go.go.Condition#getIf <em>If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' containment reference.
   * @see #getIf()
   * @generated
   */
  void setIf(IfCondition value);

  /**
   * Returns the value of the '<em><b>Elseif</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elseif</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elseif</em>' containment reference.
   * @see #setElseif(ElseIfCondition)
   * @see org.xtext.go.go.GoPackage#getCondition_Elseif()
   * @model containment="true"
   * @generated
   */
  ElseIfCondition getElseif();

  /**
   * Sets the value of the '{@link org.xtext.go.go.Condition#getElseif <em>Elseif</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elseif</em>' containment reference.
   * @see #getElseif()
   * @generated
   */
  void setElseif(ElseIfCondition value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(ElseCondition)
   * @see org.xtext.go.go.GoPackage#getCondition_Else()
   * @model containment="true"
   * @generated
   */
  ElseCondition getElse();

  /**
   * Sets the value of the '{@link org.xtext.go.go.Condition#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(ElseCondition value);

} // Condition
