/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>F</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.go.GoPackage#getF()
 * @model
 * @generated
 */
public interface F extends T
{
} // F
