/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.go.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.go.GoPackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends EObject
{
} // Greeting
