/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operations One Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.go.OperationsOneEquals#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.go.go.OperationsOneEquals#getN <em>N</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.go.GoPackage#getOperationsOneEquals()
 * @model
 * @generated
 */
public interface OperationsOneEquals extends varFor
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.go.go.GoPackage#getOperationsOneEquals_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.go.go.OperationsOneEquals#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>N</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>N</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' containment reference.
   * @see #setN(Numbers)
   * @see org.xtext.go.go.GoPackage#getOperationsOneEquals_N()
   * @model containment="true"
   * @generated
   */
  Numbers getN();

  /**
   * Sets the value of the '{@link org.xtext.go.go.OperationsOneEquals#getN <em>N</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' containment reference.
   * @see #getN()
   * @generated
   */
  void setN(Numbers value);

} // OperationsOneEquals
