/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.go.GoPackage#getOrExpression()
 * @model
 * @generated
 */
public interface OrExpression extends Expression
{
} // OrExpression
