/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>var For</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.go.GoPackage#getvarFor()
 * @model
 * @generated
 */
public interface varFor extends CallFor
{
} // varFor
