/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;

import org.xtext.go.AbstractGoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoRuntimeModule extends AbstractGoRuntimeModule {
}
