/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.go.go.DecVar;
import org.xtext.go.go.GoPackage;
import org.xtext.go.validation.AbstractGoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GoValidator extends AbstractGoValidator {
  @Check
  public void checkGreetingStartsWithCapital(final DecVar g) {
    int _size = g.getAtrb().size();
    boolean _greaterThan = (_size > 0);
    if (_greaterThan) {
      int _size_1 = g.getVars().size();
      int _size_2 = g.getAtrb().size();
      boolean _lessThan = (_size_1 < _size_2);
      if (_lessThan) {
        this.error("número de atribuições maior que variaveis", GoPackage.Literals.DEC_VAR__VARS);
      } else {
        int _size_3 = g.getVars().size();
        int _size_4 = g.getAtrb().size();
        boolean _greaterThan_1 = (_size_3 > _size_4);
        if (_greaterThan_1) {
          this.error("número de atribuições menor que variaveis", GoPackage.Literals.DEC_VAR__VARS);
        }
      }
    }
  }
}
