/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go.ide;

import org.xtext.go.ide.AbstractGoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GoIdeModule extends AbstractGoIdeModule {
}
