/*
 * generated by Xtext 2.13.0
 */
package org.xtext.go.validation

import org.eclipse.xtext.validation.Check
import org.xtext.go.go.Go
import org.xtext.go.go.DecVar
import org.xtext.go.go.GoPackage
import org.xtext.go.go.Greeting

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GoValidator extends AbstractGoValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					GoPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkGreetingStartsWithCapital(DecVar g) {
		if(g.atrb.size() > 0){
			if(g.vars.size() < g.atrb.size()){
				error("número de atribuições maior que variaveis", GoPackage.Literals.DEC_VAR__VARS);
			}else if(g.vars.size() > g.atrb.size()){
				error("número de atribuições menor que variaveis", GoPackage.Literals.DEC_VAR__VARS);
			}
		}
	}

	
}
